"""Sparse vector storage for BM25-like retrieval.

Stores and retrieves sparse embeddings generated by BGE-M3.
"""

import json
import logging
from pathlib import Path
from typing import Dict, List, Optional, Tuple

from rag_lab.config import STORAGE_DIR, SPARSE_INDEX_PATH

logger = logging.getLogger("rag_lab")


class SparseStore:
    """Sparse vector storage using JSON file."""

    def __init__(
        self,
        storage_path: Optional[Path] = None,
    ):
        """Initialize the sparse store.

        Args:
            storage_path: Path to store sparse embeddings.
        """
        self.storage_path = storage_path or SPARSE_INDEX_PATH
        self._data: Dict[str, dict] = {}
        if self.storage_path.exists():
            self.load()

    def load(self) -> None:
        """Load sparse embeddings from JSON file."""
        if self.storage_path.exists():
            with open(self.storage_path, "r", encoding="utf-8") as f:
                self._data = json.load(f)
            logger.info(f"Loaded {len(self._data)} sparse embeddings")
        else:
            logger.info("No existing sparse index found")

    def save(self) -> None:
        """Save sparse embeddings to JSON file."""
        self.storage_path.parent.mkdir(parents=True, exist_ok=True)
        with open(self.storage_path, "w", encoding="utf-8") as f:
            json.dump(self._data, f, ensure_ascii=False)
        logger.info(f"Saved {len(self._data)} sparse embeddings to {self.storage_path}")

    def add(
        self,
        ids: List[str],
        sparse_vectors: List[dict],
    ) -> None:
        """Add sparse vectors to the store.

        Args:
            ids: List of unique IDs.
            sparse_vectors: List of sparse vector dicts.
        """
        for i, id_ in enumerate(ids):
            self._data[id_] = {
                "sparse": sparse_vectors[i],
            }
        logger.info(f"Added {len(ids)} sparse vectors")

    def query(
        self,
        query_sparse: dict,
        top_k: int = 20,
    ) -> List[dict]:
        """Query the sparse store.

        Args:
            query_sparse: Sparse vector for the query.
            top_k: Number of results to return.

        Returns:
            List of matching entries with scores.
        """
        # Simple dot product similarity
        results = []
        for id_, entry in self._data.items():
            score = self._compute_similarity(query_sparse, entry["sparse"])
            results.append({
                "id": id_,
                "score": score,
            })

        # Sort by score descending
        results.sort(key=lambda x: x["score"], reverse=True)
        return results[:top_k]

    def _compute_similarity(
        self,
        query_sparse: dict,
        doc_sparse: dict,
    ) -> float:
        """Compute similarity between two sparse vectors.

        Args:
            query_sparse: Query sparse vector.
            doc_sparse: Document sparse vector.

        Returns:
            Similarity score.
        """
        score = 0.0
        for key, val in query_sparse.items():
            if key in doc_sparse:
                score += val * doc_sparse[key]
        return score

    def count(self) -> int:
        """Return the number of sparse vectors stored."""
        return len(self._data)