"""Post-processing: verify citations generated by the LLM.

Checks that cited chunk IDs and heading paths match actual chunks.
Uses fuzzy matching since the LLM often cites abbreviated paths.
"""

import logging
import re
from typing import List, Tuple

logger = logging.getLogger("rag_lab")


def verify_citations(
    response: str,
    valid_chunks: List[dict],
) -> str:
    """Verify and fix citations in the LLM's response.

    Args:
        response: The LLM's response text.
        valid_chunks: List of valid chunk dicts.

    Returns:
        The verified response text.
    """
    # Extract all citations from the response
    # Support both legacy format [DOC: ..., Sección: ...] and new format [[N] Fuente: ...]
    legacy_pattern = r'\[DOC:\s*([^,\]]+),\s*Sección:\s*([^\]]+)\]'
    new_pattern = r'\[\[(\d+)\]\s*Fuente:\s*([^|]+)\|\s*Sección:\s*([^|]+)\|\s*Líneas:\s*(\d+)-(\d+)\]'
    
    legacy_citations = re.findall(legacy_pattern, response)
    new_citations = re.findall(new_pattern, response)

    # Get valid chunk IDs and heading paths
    valid_ids = {c.get("doc_id", "") for c in valid_chunks}
    valid_paths = {c.get("heading_path", "") for c in valid_chunks}
    # Also collect text bodies for fallback matching — with sibling merging,
    # the LLM may cite a heading visible inside the chunk text body
    # (e.g., "## 4.2.6 Standard Reporting Period") even though the
    # chunk's metadata heading_path is different.
    chunk_texts = [c.get("text", "") for c in valid_chunks]

    valid_count = 0
    invalid_count = 0

    # Process legacy citations [DOC: ..., Sección: ...]
    for doc_id, heading_path in legacy_citations:
        doc_id = doc_id.strip()
        heading_path = heading_path.strip()

        # Verify doc_id
        if doc_id not in valid_ids:
            logger.warning(f"Invalid citation DOC: {doc_id}")
            invalid_count += 1
            continue

        # Verify heading_path with fuzzy matching against metadata paths
        if _fuzzy_match_path(heading_path, valid_paths):
            valid_count += 1
        # Fallback: check if the cited section appears inside any chunk's text
        elif _found_in_chunk_text(heading_path, chunk_texts):
            valid_count += 1
        else:
            logger.warning(f"Invalid citation: Sección:{heading_path}")
            invalid_count += 1

    # Process new citations [[N] Fuente: ...]
    for index, doc_id, heading_path, line_start, line_end in new_citations:
        doc_id = doc_id.strip()
        heading_path = heading_path.strip()

        # Verify doc_id
        if doc_id not in valid_ids:
            logger.warning(f"Invalid citation DOC: {doc_id}")
            invalid_count += 1
            continue

        # Verify heading_path with fuzzy matching against metadata paths
        if _fuzzy_match_path(heading_path, valid_paths):
            valid_count += 1
        # Fallback: check if the cited section appears inside any chunk's text
        elif _found_in_chunk_text(heading_path, chunk_texts):
            valid_count += 1
        else:
            logger.warning(f"Invalid citation: Sección:{heading_path}")
            invalid_count += 1

    logger.info(f"Verified {valid_count + invalid_count} citations ({valid_count} valid, {invalid_count} invalid)")
    return response


def _fuzzy_match_path(cited_path: str, valid_paths: set) -> bool:
    """Check if a cited path matches any valid path.

    Supports:
    - Exact match
    - Substring match (LLM cites "3.3.1" and valid is "3.3.1 Format Optimizations...")
    - Partial heading match (LLM cites first words of the heading)

    Args:
        cited_path: The heading path cited by the LLM.
        valid_paths: Set of valid heading paths.

    Returns:
        True if the citation matches a valid path.
    """
    cited_lower = cited_path.strip().lower()

    for valid_path in valid_paths:
        valid_lower = valid_path.strip().lower()

        # Exact match
        if cited_lower == valid_lower:
            return True

        # Cited path is a prefix of a valid path
        if valid_lower.startswith(cited_lower):
            return True

        # Cited path appears anywhere in a valid path
        if cited_lower in valid_lower:
            return True

        # Valid path starts with the cited path (numbered sections)
        # e.g., cited "3.3.1" matches "3.3.1 Format Optimizations..."
        if valid_lower.startswith(cited_lower.rstrip()):
            return True

    return False


def _found_in_chunk_text(cited_path: str, chunk_texts: list) -> bool:
    """Check if the cited section heading appears inside any chunk's text.

    With sibling merging, a chunk may contain internal headings like
    '## 4.2.6 Standard Reporting Period' that are not in the metadata
    heading_path. The LLM reads these and cites them — which is valid.

    Args:
        cited_path: The heading path cited by the LLM.
        chunk_texts: List of chunk text bodies.

    Returns:
        True if the cited heading appears in any chunk text.
    """
    cited_lower = cited_path.strip().lower()

    for text in chunk_texts:
        text_lower = text.lower()
        # Check as inline heading (e.g., "## 4.2.6 Standard Reporting Period")
        if cited_lower in text_lower:
            return True

    return False